# Travis CI configuration file for running tests
sudo: false
language: python
branches:
    only:
      - master
python:
  - 3.6
  - 3.8
install:
  - pip install -r requirements/travis.txt
script:
  - pycodestyle .
  - pylint tests
